### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by blryface**

### CODE REVIEW

**Review by KTrain5169 — CHANGES_REQUESTED** [review]
~~ja_ja should be renamed to ja_jp, will change in a bit~~

nvm I just checked the amount of other stuff I have to do before friday

**Comment by blryface** [comment]
h

**Comment by NormalFery** [comment]
Is this supposed to remove 2 random strings from the es_ar translation? @KTrain5169

**Comment by blryface** [comment]
It's not tho?

**Comment by KTrain5169** [comment]
> Is this supposed to remove 2 random strings from the es_ar translation? @KTrain5169

Probably not but blryface committed a fix so 🤷

**Comment by blryface** [comment]
@KTrain5169 eta fix or smth (pls help)

**Comment by blryface** [comment]
hm

**Comment by KTrain5169** [comment]
BACK TO GITHUB CHAT WE GO

@blryface is ja_jp.json the japanese lang file for minecraft?

**Review by KTrain5169 — APPROVED** [review]
pretty sure this is how it works now

**Comment by blryface** [comment]
dytfyjvfdjj;-ff_jkcdtippkjhh

**Pull request merged**
